import {
    addDays,
    addMonths,
    endOfMonth,
    startOfDay,
    startOfMonth,
    subDays,
    subMonths,
  } from 'date-fns';
  const today = startOfDay(new Date());
  
  export const exampleStatuses = [
    { id: 'todo', name: 'To Do', color: '#6B7280' },
    { id: 'inprogress', name: 'In Progress', color: '#3B82F6' },
    { id: 'done', name: 'Done', color: '#10B981' },
  ];
  
  const owner = {
    id: 'dev_1',
    name: 'Indie Dev',
  };
  
  const projects = {
    saasApp: { id: 'proj_saas', name: 'My Awesome SaaS' },
    game: { id: 'proj_game', name: 'Pixel Adventure Game' },
    blog: { id: 'proj_blog', name: 'Dev Blog' },
    learning: { id: 'proj_learn', name: 'Skill Ups' },
    portfolio: { id: 'proj_portfolio', name: 'Portfolio Site' },
  };
  
  const groups = {
    frontend: { id: 'grp_frontend', name: 'Frontend' },
    backend: { id: 'grp_backend', name: 'Backend' },
    infra: { id: 'grp_infra', name: 'Infrastructure' },
    gameplay: { id: 'grp_gameplay', name: 'Gameplay' },
    art: { id: 'grp_art', name: 'Art/Assets' },
    marketing: { id: 'grp_marketing', name: 'Marketing' },
    content: { id: 'grp_content', name: 'Content Creation' },
    learning: { id: 'grp_learning', name: 'Learning' },
    admin: { id: 'grp_admin', name: 'Admin' },
  };
  
  const initiatives = {
    mvp: { id: 'init_mvp', name: 'MVP Launch' },
    refactor: { id: 'init_refactor', name: 'Code Refactor' },
    skillDev: { id: 'init_skill', name: 'Skill Development' },
    audience: { id: 'init_audience', name: 'Build Audience' },
    maintenance: { id: 'init_maint', name: 'Maintenance' },
  };
  
  const releases = {
    alpha: { id: 'rel_alpha', name: 'Alpha Build' },
    beta: { id: 'rel_beta', name: 'Beta Release' },
    v1: { id: 'rel_v1', name: 'v1.0 Launch' },
    q3: { id: 'rel_q3', name: 'Q3 Goals' },
    q4: { id: 'rel_q4', name: 'Q4 Goals' },
  };
  
  // Helper function to generate DiceBear URLs
  const generateEmoji = (seed: number) => ({
    url: `https://api.dicebear.com/7.x/adventurer/svg?seed=${seed}`,
    style: 'adventurer',
    seed: seed
  });
  
  export const exampleFeatures = [
    {
      id: 'task_1',
      name: 'Setup CI/CD Pipeline',
      startAt: startOfMonth(subMonths(today, 1)),
      endAt: addDays(startOfMonth(subMonths(today, 1)), 5),
      status: exampleStatuses[0],
      group: groups.infra,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.alpha,
      emoji: generateEmoji(101),
    },
    {
      id: 'task_2',
      name: 'Design Database Schema',
      startAt: addDays(startOfMonth(subMonths(today, 1)), 6),
      endAt: addDays(startOfMonth(subMonths(today, 1)), 10),
      status: exampleStatuses[0],
      group: groups.backend,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.alpha,
      emoji: generateEmoji(102),
    },
    {
      id: 'task_3',
      name: 'Implement User Authentication (Backend)',
      startAt: subDays(today, 10),
      endAt: addDays(today, 5),
      status: exampleStatuses[2],
      group: groups.backend,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.beta,
      emoji: generateEmoji(103),
    },
    {
      id: 'task_4',
      name: 'Build Login/Signup UI',
      startAt: today,
      endAt: addDays(today, 14),
      status: exampleStatuses[1],
      group: groups.frontend,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.beta,
      emoji: generateEmoji(104),
    },
    {
      id: 'task_5',
      name: 'Create Landing Page Design',
      startAt: addDays(today, 7),
      endAt: addDays(today, 21),
      status: exampleStatuses[0],
      group: groups.frontend,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.beta,
      emoji: generateEmoji(105),
    },
    {
      id: 'task_6',
      name: 'Write API documentation',
      startAt: addMonths(today, 1),
      endAt: addDays(addMonths(today, 1), 10),
      status: exampleStatuses[0],
      group: groups.backend,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.v1,
      emoji: generateEmoji(106),
    },
    {
      id: 'task_7',
      name: 'Prototype Core Jump Mechanic',
      startAt: subDays(today, 20),
      endAt: subDays(today, 15),
      status: exampleStatuses[0],
      group: groups.gameplay,
      product: projects.game,
      initiative: initiatives.mvp,
      release: releases.alpha,
      emoji: generateEmoji(107),
    },
    {
      id: 'task_8',
      name: 'Create Main Character Sprite Sheet',
      startAt: subDays(today, 14),
      endAt: addDays(today, 3),
      status: exampleStatuses[2],
      group: groups.art,
      product: projects.game,
      initiative: initiatives.mvp,
      release: releases.alpha,
      emoji: generateEmoji(108),
    },
    {
      id: 'task_9',
      name: 'Design Level 1 Layout',
      startAt: today,
      endAt: addDays(today, 10),
      status: exampleStatuses[1],
      group: groups.gameplay,
      product: projects.game,
      initiative: initiatives.mvp,
      release: releases.beta,
      emoji: generateEmoji(109),
    },
    {
      id: 'task_10',
      name: 'Compose Main Theme Music',
      startAt: addDays(today, 5),
      endAt: addDays(today, 19),
      status: exampleStatuses[0],
      group: groups.art,
      product: projects.game,
      initiative: initiatives.mvp,
      release: releases.beta,
      emoji: generateEmoji(110),
    },
    {
      id: 'task_11',
      name: 'Write Blog Post: "Intro to SolidJS"',
      startAt: subDays(today, 5),
      endAt: addDays(today, 2),
      status: exampleStatuses[0],
      group: groups.content,
      product: projects.blog,
      initiative: initiatives.audience,
      release: releases.q3,
      emoji: generateEmoji(111),
    },
    {
      id: 'task_12',
      name: 'Update Portfolio with Latest Project',
      startAt: addDays(today, 1),
      endAt: addDays(today, 6),
      status: exampleStatuses[1],
      group: groups.admin,
      product: projects.portfolio,
      initiative: initiatives.maintenance,
      release: releases.q3,
      emoji: generateEmoji(112),
    },
    {
      id: 'task_13',
      name: 'Complete "Advanced TypeScript" Course Module',
      startAt: today,
      endAt: addDays(today, 14),
      status: exampleStatuses[2],
      group: groups.learning,
      product: projects.learning,
      initiative: initiatives.skillDev,
      release: releases.q3,
      emoji: generateEmoji(113),
    },
    {
      id: 'task_14',
      name: 'Research Cloud Hosting Options',
      startAt: addDays(today, 10),
      endAt: addDays(today, 17),
      status: exampleStatuses[0],
      group: groups.infra,
      product: projects.saasApp,
      initiative: initiatives.mvp,
      release: releases.beta,
      emoji: generateEmoji(114),
    },
    {
      id: 'task_15',
      name: 'Fix Bug #42: Image upload fails on mobile',
      startAt: subDays(today, 2),
      endAt: today,
      status: exampleStatuses[0],
      group: groups.frontend,
      product: projects.portfolio,
      initiative: initiatives.maintenance,
      release: releases.q3,
      emoji: generateEmoji(115),
    },
    {
      id: 'task_16',
      name: 'Plan Social Media Content for Game Launch',
      startAt: addMonths(today, 1),
      endAt: addDays(addMonths(today, 1), 14),
      status: exampleStatuses[0],
      group: groups.marketing,
      product: projects.game,
      initiative: initiatives.audience,
      release: releases.v1,
      emoji: generateEmoji(116),
    },
    {
      id: 'task_17',
      name: 'Refactor Authentication Service',
      startAt: addDays(today, 20),
      endAt: addDays(addMonths(today, 1), 10),
      status: exampleStatuses[0],
      group: groups.backend,
      product: projects.saasApp,
      initiative: initiatives.refactor,
      release: releases.q4,
      emoji: generateEmoji(117),
    },
  ];
  
  export const exampleMarkers = [
    {
      id: 'm1',
      date: startOfMonth(subMonths(today, 1)),
      label: 'Project SaaS Kickoff',
      className: 'bg-blue-100 text-blue-900 border-blue-300',
    },
    {
      id: 'm2',
      date: today,
      label: 'Today',
      className: 'bg-primary/10 text-primary border-primary/30',
    },
    {
      id: 'm3',
      date: endOfMonth(addMonths(today, 1)),
      label: 'Beta Target',
      className: 'bg-amber-100 text-amber-900 border-amber-300',
    },
    {
      id: 'm4',
      date: startOfMonth(addMonths(today, 3)),
      label: 'SaaS v1 Launch Goal',
      className: 'bg-red-100 text-red-900 border-red-300',
    },
    {
      id: 'm5',
      date: endOfMonth(addMonths(today, 4)),
      label: 'Game Launch Goal',
      className: 'bg-purple-100 text-purple-900 border-purple-300',
    },
  ];